# Generated by Django 6.0.6 on 2026-09-06 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('user', '普通用户'), ('dept_admin', '部门管理员')], default='user', help_text='部门管理员可管理本部门的知识库（建库/上传/改名/删除）；普通用户只读。', max_length=20, verbose_name='账号级别'),
        ),
    ]
