# Generated by Django 6.0.6 on 2026-08-21 14:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kb', '0008_knowledgebase_is_folder_knowledgebase_parent'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StructuredDataset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160, verbose_name='数据集名称')),
                ('kind', models.CharField(choices=[('downtime', 'Downtime 停机'), ('apex', 'APEX'), ('parts', '部件信息'), ('drawing', '图纸 / G-code / SCP'), ('other', '其它关联表')], max_length=20, verbose_name='数据类型')),
                ('source_name', models.CharField(max_length=255, verbose_name='来源文件')),
                ('checksum', models.CharField(db_index=True, max_length=64, verbose_name='文件校验值')),
                ('row_count', models.PositiveIntegerField(default=0, verbose_name='数据行数')),
                ('mapping', models.JSONField(blank=True, default=dict, verbose_name='识别到的字段映射')),
                ('active', models.BooleanField(db_index=True, default=True, verbose_name='当前版本')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('imported_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='structured_datasets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '结构化数据集',
                'verbose_name_plural': '结构化数据集',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StructuredRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sheet_name', models.CharField(blank=True, default='', max_length=120, verbose_name='工作表')),
                ('row_number', models.PositiveIntegerField(default=0, verbose_name='原始行号')),
                ('drawing_no', models.CharField(blank=True, default='', max_length=160, verbose_name='图纸号')),
                ('drawing_no_norm', models.CharField(blank=True, db_index=True, default='', max_length=160)),
                ('part_no', models.CharField(blank=True, default='', max_length=160, verbose_name='部件号')),
                ('part_no_norm', models.CharField(blank=True, db_index=True, default='', max_length=160)),
                ('part_name', models.CharField(blank=True, default='', max_length=255, verbose_name='部件名称')),
                ('part_name_norm', models.CharField(blank=True, db_index=True, default='', max_length=255)),
                ('g_code', models.CharField(blank=True, default='', max_length=160, verbose_name='G-code')),
                ('g_code_norm', models.CharField(blank=True, db_index=True, default='', max_length=160)),
                ('scp_level', models.CharField(blank=True, default='', max_length=80, verbose_name='SCP 等级')),
                ('equipment', models.CharField(blank=True, default='', max_length=200, verbose_name='设备/资产')),
                ('equipment_norm', models.CharField(blank=True, db_index=True, default='', max_length=200)),
                ('apex_no', models.CharField(blank=True, default='', max_length=160, verbose_name='APEX 编号')),
                ('apex_no_norm', models.CharField(blank=True, db_index=True, default='', max_length=160)),
                ('raw_data', models.JSONField(default=dict, verbose_name='原始行数据')),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='kb.structureddataset')),
            ],
            options={
                'verbose_name': '结构化数据记录',
                'verbose_name_plural': '结构化数据记录',
                'ordering': ['dataset_id', 'sheet_name', 'row_number'],
            },
        ),
        migrations.AddIndex(
            model_name='structureddataset',
            index=models.Index(fields=['kind', 'active'], name='kb_structur_kind_8c6a50_idx'),
        ),
        migrations.AddIndex(
            model_name='structuredrecord',
            index=models.Index(fields=['dataset', 'row_number'], name='kb_structur_dataset_582f39_idx'),
        ),
    ]
