# Generated by Django 6.0.6 on 2026-08-24 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kb', '0009_structureddataset_structuredrecord_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='knowledgebase',
            name='department',
            field=models.CharField(default='通用', max_length=50, verbose_name='部门'),
        ),
    ]
