# Generated by Django 6.0.6 on 2026-09-06 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kb', '0010_knowledgebase_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='knowledgebase',
            name='embedding_dimensions',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='向量维度'),
        ),
        migrations.AddField(
            model_name='knowledgebase',
            name='embedding_model',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='向量模型'),
        ),
    ]
