# Generated by Django 6.0.6 on 2026-09-06 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kb', '0011_knowledgebase_embedding_dimensions_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfig',
            name='active_preset_embedding',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='active_preset_llm',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='active_preset_mineru',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='active_preset_retrieval',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
