# Generated by Django 6.0.6 on 2026-09-06 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kb', '0012_siteconfig_active_preset_embedding_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EvalQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(help_text='模拟真实检索的问法', verbose_name='问题')),
                ('expected_source', models.CharField(blank=True, default='', max_length=255, verbose_name='期望文档')),
                ('expected_keyword', models.CharField(blank=True, default='', max_length=255, verbose_name='期望关键词')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '评估问题',
                'verbose_name_plural': '评估问题',
                'ordering': ['-created_at'],
            },
        ),
    ]
