# Generated by Django 6.0.6 on 2026-09-06 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kb', '0013_evalquestion'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfig',
            name='active_preset_rerank',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='rerank_base_url',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Rerank Base URL'),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='rerank_enabled',
            field=models.BooleanField(default=False, verbose_name='启用重排序'),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='rerank_model',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Rerank 模型'),
        ),
        migrations.AlterField(
            model_name='configpreset',
            name='category',
            field=models.CharField(choices=[('llm', 'LLM'), ('embedding', '向量模型'), ('retrieval', '检索参数'), ('mineru', 'MinerU OCR'), ('rerank', '重排序')], default='llm', max_length=20, verbose_name='分类'),
        ),
    ]
