# Generated by Django 6.0.6 on 2026-09-06 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kb', '0014_siteconfig_active_preset_rerank_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfig',
            name='rerank_api_key',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Rerank API Key'),
        ),
    ]
