# Generated by Django 6.0.6 on 2026-09-07 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kb', '0015_siteconfig_rerank_api_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='description',
            field=models.TextField(blank=True, default='', help_text='可选；会展示给 AI 帮其判断该文档与问题的相关性', verbose_name='描述'),
        ),
    ]
