# Generated by Django 6.0.6 on 2026-09-08 05:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kb', '0016_document_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='KbTracker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=False, verbose_name='启用')),
                ('fields', models.JSONField(blank=True, default=list, verbose_name='追踪字段')),
                ('instruction', models.TextField(blank=True, default='', help_text='追加到抽取提示词，例如：结论只填 合格/不合格', max_length=500, verbose_name='补充提示')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kb', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tracker', to='kb.knowledgebase', verbose_name='知识库')),
            ],
            options={
                'verbose_name': '追踪表',
                'verbose_name_plural': '追踪表',
            },
        ),
        migrations.CreateModel(
            name='TrackerRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('values', models.JSONField(blank=True, default=dict, verbose_name='抽取值')),
                ('status', models.CharField(choices=[('pending', '待抽取'), ('running', '抽取中'), ('done', '已完成'), ('failed', '失败')], default='pending', max_length=12, verbose_name='状态')),
                ('error', models.CharField(blank=True, default='', max_length=300, verbose_name='错误')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracker_rows', to='kb.document')),
                ('tracker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rows', to='kb.kbtracker')),
            ],
            options={
                'verbose_name': '追踪记录',
                'verbose_name_plural': '追踪记录',
                'ordering': ['-document__created_at'],
                'unique_together': {('tracker', 'document')},
            },
        ),
    ]
