# Generated by Django 6.0.6 on 2026-09-08 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kb', '0017_kbtracker_trackerrow'),
    ]

    operations = [
        migrations.AddField(
            model_name='kbtracker',
            name='schema_version',
            field=models.PositiveIntegerField(default=0, verbose_name='字段结构版本'),
        ),
        migrations.AddField(
            model_name='trackerrow',
            name='proposed_values',
            field=models.JSONField(blank=True, default=dict, verbose_name='待确认的新值'),
        ),
        migrations.AddField(
            model_name='trackerrow',
            name='schema_version',
            field=models.PositiveIntegerField(default=0, verbose_name='抽取时的字段结构版本'),
        ),
        migrations.AlterField(
            model_name='trackerrow',
            name='status',
            field=models.CharField(choices=[('pending', '待抽取'), ('running', '抽取中'), ('proposed', '待确认'), ('done', '已完成'), ('failed', '失败')], default='pending', max_length=12, verbose_name='状态'),
        ),
    ]
