# Generated by Django 6.0.6 on 2026-09-09 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kb', '0018_kbtracker_schema_version_trackerrow_proposed_values_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfig',
            name='llm_vision',
            field=models.BooleanField(default=False, verbose_name='LLM 支持图片输入'),
        ),
    ]
