# Generated by Django 6.0.6 on 2026-09-11 10:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kb', '0019_siteconfig_llm_vision'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfig',
            name='qa_enhance',
            field=models.BooleanField(default=False, verbose_name='问答管线增强（规划 + 核实）'),
        ),
        migrations.CreateModel(
            name='ChunkProvenance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chunk_id', models.CharField(max_length=160, unique=True, verbose_name='Chroma 向量 ID')),
                ('kb_slug', models.CharField(blank=True, db_index=True, default='', max_length=100, verbose_name='所属库 slug')),
                ('page_start', models.PositiveIntegerField(default=0, verbose_name='起始页（0 基）')),
                ('page_end', models.PositiveIntegerField(default=0, verbose_name='结束页（0 基）')),
                ('blocks', models.JSONField(blank=True, default=list, verbose_name='定位块列表')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='provenance', to='kb.document')),
            ],
            options={
                'verbose_name': 'chunk 溯源',
                'verbose_name_plural': 'chunk 溯源',
                'indexes': [models.Index(fields=['document', 'page_start'], name='kb_chunkpro_documen_0b8858_idx')],
            },
        ),
    ]
