# Generated by Django 6.0.6 on 2026-09-11 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kb', '0020_siteconfig_qa_enhance_chunkprovenance'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='page_embed',
            field=models.BooleanField(default=False, verbose_name='整页视觉入库'),
        ),
    ]
