# Generated by Django 6.0.6 on 2026-09-16 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kb', '0022_message_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='completion_status',
            field=models.CharField(choices=[('complete', '完整'), ('incomplete', '未完成')], default='complete', max_length=12, verbose_name='回答状态'),
        ),
    ]
